const fs = require('fs');

let content = fs.readFileSync('src/App.tsx', 'utf8');

const replacements = {
  // Core
  'AI LOAD': 'НАГРУЗКА ИИ',
  'REAL-TIME': 'В РЕАЛЬНОМ ВРЕМЕНИ',
  'RISK SCORE': 'ИНДЕКС РИСКА',
  'AUTONOMY': 'АВТОНОМИЯ',
  'LEVEL 4': 'УРОВЕНЬ 4',
  'MEMORY USE': 'ИСПОЛЬЗОВАНИЕ ПАМЯТИ',
  'CONFIDENCE': 'УВЕРЕННОСТЬ',
  'STABLE': 'СТАБИЛЬНО',
  'INTEGRITY': 'ЦЕЛОСТНОСТЬ',
  'SECURE': 'БЕЗОПАСНО',
  'AI Orchestrator': 'ИИ-Оркестратор',
  'Decision Engine Performance': 'Производительность модуля принятия решений',
  'Decision Engine Log': 'Журнал модуля принятия решений',
  'Risk recalculation triggered': 'Запущен перерасчет рисков',
  'LOW_RISK': 'НИЗКИЙ РИСК',
  'Quantum Core Sync': 'Синхронизация квантового ядра',
  'SUCCESS': 'УСПЕШНО',
  'Behavioral Pattern Match': 'Совпадение поведенческого паттерна',
  'VERIFIED': 'ПРОВЕРЕНО',
  'Autonomous Action: Climate': 'Автономное действие: Климат',
  'EXECUTED': 'ВЫПОЛНЕНО',
  'Neural Pattern Update': 'Обновление нейронного паттерна',
  'PENDING': 'ОЖИДАНИЕ',
  'Adaptive Learning': 'Адаптивное обучение',
  'Pattern Recognition': 'Распознавание паттернов',
  'Behavioral Modeling': 'Поведенческое моделирование',
  'Context Awareness': 'Контекстная осведомленность',
  'Predictive Accuracy': 'Точность прогнозирования',
  'Risk Engine': 'Модуль анализа рисков',
  'Physical Security': 'Физическая безопасность',
  'Digital Threats': 'Цифровые угрозы',
  'Health Risks': 'Риски для здоровья',
  'Environmental': 'Окружающая среда',
  'Activity Stream': 'Поток активности',
  'Live': 'В эфире',
  'Proactive suggestion: Schedule recovery time after high-stress period': 'Проактивное предложение: Запланируйте время восстановления после периода высокого стресса',
  'Heart rate normalized — stress indicators declining': 'Пульс нормализован — показатели стресса снижаются',
  'Motion detected at front entrance — verified as delivery': 'Обнаружено движение у главного входа — подтверждена доставка',
  'System integrity check complete: 97% stable': 'Проверка целостности системы завершена: стабильность 97%',

  // Voice
  'LISTENING...': 'СЛУШАЮ...',
  "STANDBY - SAY 'HEY AURION'": "ОЖИДАНИЕ - СКАЖИТЕ 'ПРИВЕТ AURION'",
  'Show system status': 'Показать статус системы',
  'Check security': 'Проверить безопасность',
  'Health report': 'Отчет о здоровье',
  'Smart home status': 'Статус умного дома',
  'What are my reminders?': 'Какие у меня напоминания?',
  'Activate guardian mode': 'Активировать режим стража',
  'Type a message to Jarvoice...': 'Введите сообщение для Джарвойса...',
  'Voice Intent Analysis': 'Анализ голосовых намерений',
  'Query': 'Запрос',
  'Command': 'Команда',
  'Alert': 'Тревога',
  'Social': 'Социальное',
  'User': 'Пользователь',

  // Memory
  'Memory System': 'Система памяти',
  'Vector DB': 'Векторная БД',
  'Episodic Storage': 'Эпизодическое хранилище',
  'Semantic Search': 'Семантический поиск',
  'Search memories...': 'Поиск воспоминаний...',
  'Memory Nodes': 'Узлы памяти',
  'Core Beliefs': 'Базовые убеждения',
  'Recent Events': 'Недавние события',
  'Skills & Habits': 'Навыки и привычки',
  'Preferences': 'Предпочтения',
  'Memory Consolidation': 'Консолидация памяти',
  'Short-term to Long-term transfer': 'Перенос из краткосрочной в долгосрочную',
  'Pruning irrelevant data': 'Удаление нерелевантных данных',
  'Optimizing retrieval paths': 'Оптимизация путей извлечения',
  'ACTIVE': 'АКТИВНО',
  'COMPLETED': 'ЗАВЕРШЕНО',

  // Home
  'Smart Home': 'Умный дом',
  'Scene Presets': 'Сценарии',
  'Energy Management': 'Управление энергией',
  'Morning Routine': 'Утренний режим',
  'Deep Focus': 'Глубокая концентрация',
  'Evening Relax': 'Вечерний отдых',
  'Security Lockdown': 'Блокировка безопасности',
  'Climate Control': 'Климат-контроль',
  'Living Room': 'Гостиная',
  'Bedroom': 'Спальня',
  'Office': 'Кабинет',
  'Kitchen': 'Кухня',
  'Energy Consumption': 'Энергопотребление',
  'Current Usage': 'Текущее использование',
  'Solar Generation': 'Солнечная генерация',
  'Battery Reserve': 'Резерв батареи',
  'Grid Draw': 'Потребление от сети',

  // Health
  'Health Intelligence': 'Аналитика здоровья',
  'Vital Signs': 'Жизненные показатели',
  'AI Recommendations': 'Рекомендации ИИ',
  'Heart Rate': 'Пульс',
  'Blood Oxygen': 'Кислород в крови',
  'Stress Level': 'Уровень стресса',
  'Sleep Quality': 'Качество сна',
  'BPM': 'УД/МИН',
  'NORMAL': 'В НОРМЕ',
  'ELEVATED': 'ПОВЫШЕН',
  'OPTIMAL': 'ОПТИМАЛЬНО',
  'Health Insights': 'Анализ здоровья',
  'Hydration low. Recommend 500ml water intake.': 'Низкая гидратация. Рекомендуется выпить 500 мл воды.',
  'Sleep deficit detected. Suggesting 30m nap at 14:00.': 'Обнаружен дефицит сна. Предлагаю 30-минутный сон в 14:00.',
  'Stress trending up. Initiating ambient relaxation protocol.': 'Уровень стресса растет. Запускаю протокол фоновой релаксации.',
  'Workout Readiness': 'Готовность к тренировке',
  'Recovery': 'Восстановление',
  'Strain': 'Нагрузка',
  'Energy': 'Энергия',

  // Reminder
  'Reminder Engine': 'Модуль напоминаний',
  'Task Management': 'Управление задачами',
  'Priority Queue': 'Очередь приоритетов',
  'Upcoming Tasks': 'Предстоящие задачи',
  'Review Q3 Financials': 'Обзор финансов за 3 квартал',
  'Call Sarah': 'Позвонить Саре',
  'Take Supplements': 'Принять витамины',
  'Gym Session': 'Тренировка в зале',
  'HIGH': 'ВЫСОКИЙ',
  'MEDIUM': 'СРЕДНИЙ',
  'LOW': 'НИЗКИЙ',
  'Task Distribution': 'Распределение задач',
  'Total': 'Всего',
  'Active': 'Активные',
  'Completed': 'Завершенные',
  'Ignored': 'Проигнорированные',
  'Ignore Analysis': 'Анализ игнорирования',
  'Medical reminders are ignored in 67% of cases. Suggesting time shift to 08:00 for better adherence.': 'Медицинские напоминания игнорируются в 67% случаев. Предлагаю перенести время на 08:00 для лучшего соблюдения.',
  'Critical Adherence Issue': 'Критическая проблема соблюдения',

  // Twin
  'Digital Twin': 'Цифровой двойник',
  'User Profile': 'Профиль пользователя',
  'System Influence': 'Влияние на систему',
  'Analytical-Proactive': 'Аналитический-Проактивный',
  'Data-Driven': 'Основан на данных',
  'Emotionally Stable': 'Эмоционально стабилен',
  'High Focus': 'Высокая концентрация',
  'Productivity': 'Продуктивность',
  'Health Score': 'Индекс здоровья',
  'Risk Tolerance': 'Толерантность к риску',
  'Social Impact': 'Социальное влияние',
  'Twin Influence': 'Влияние двойника',
  'Module Impact Analysis': 'Анализ влияния на модули',
  'Decision Engine': 'Модуль принятия решений',
  'Autonomy Layer': 'Уровень автономии',
  'Social & Cloud': 'Социальные сети и Облако',
  'High influence on autonomous decisions.': 'Высокое влияние на автономные решения.',
  'Moderate influence on automation levels.': 'Умеренное влияние на уровни автоматизации.',
  'Critical influence on health recommendations.': 'Критическое влияние на рекомендации по здоровью.',
  'Low influence on contact filtering.': 'Низкое влияние на фильтрацию контактов.',

  // Autonomy
  'Self-Initiated Actions': 'Самостоятельные действия',
  'Neural Interface': 'Нейроинтерфейс',
  'Pending Suggestions': 'Ожидающие предложения',
  'Optimize energy consumption by 15%': 'Оптимизировать энергопотребление на 15%',
  'Update smart home security protocols': 'Обновить протоколы безопасности умного дома',
  'Schedule meeting with financial analyst': 'Запланировать встречу с финансовым аналитиком',
  'Priority:': 'Приоритет:',
  'Accept': 'Принять',
  'Dismiss': 'Отклонить',
  'Climate optimization in Living Room': 'Оптимизация климата в гостиной',
  'Security scan of external perimeter': 'Сканирование внешнего периметра безопасности',
  'Automated backup to AURION Cloud': 'Автоматическое резервное копирование в AURION Cloud',
  'Autonomy Level': 'Уровень автономии',
  'PASSIVE': 'ПАССИВНЫЙ',
  'ADVISORY': 'РЕКОМЕНДАТЕЛЬНЫЙ',
  'SEMI-AUTO': 'ПОЛУАВТОМАТ.',
  'FULL AUTO': 'ПОЛНЫЙ АВТОМАТ',
  'SOVEREIGN': 'СУВЕРЕННЫЙ',
  'Eye Tracking': 'Отслеживание взгляда',
  'Gesture Control': 'Управление жестами',
  'BCI Link': 'Нейроинтерфейс (BCI)',
  'Proximity': 'Датчик приближения',

  // Social
  'Communication Stream': 'Поток коммуникаций',
  'Cloud Sync': 'Облачная синхронизация',
  'Contacts': 'Контакты',
  'Medical': 'Медицина',
  'Family': 'Семья',
  'Colleague': 'Коллега',
  'Friend': 'Друг',
  'ONLINE': 'В СЕТИ',
  'AWAY': 'НЕТ НА МЕСТЕ',
  'BUSY': 'ЗАНЯТ',
  'OFFLINE': 'НЕ В СЕТИ',
  'SYNCED': 'СИНХРОНИЗИРОВАНО',
  'The quantum stability report is ready for review.': 'Отчет о квантовой стабильности готов к проверке.',
  'Weekly security audit completed. No threats detected.': 'Еженедельный аудит безопасности завершен. Угроз не обнаружено.',
  'Are we still on for dinner tonight?': 'Наши планы на ужин сегодня в силе?',
  'INCOMING': 'ВХОДЯЩЕЕ',
  'SYSTEM': 'СИСТЕМА',
  'Calendar Today': 'Календарь на сегодня',
  'Quantum Sync Review': 'Проверка квантовой синхронизации',
  'Lunch with Sarah': 'Обед с Сарой',
  'System Maintenance': 'Обслуживание системы',
  'Dinner': 'Ужин',
  'WORK': 'РАБОТА',
  'PERSONAL': 'ЛИЧНОЕ',
  'Google Drive': 'Google Диск',

  // Media
  'Multimedia Core': 'Мультимедийное ядро',
  'Playback Control': 'Управление воспроизведением',
  'AI Picks': 'Подборки ИИ',
  'Now Playing': 'Сейчас играет',
  'Quantum Resonance': 'Квантовый резонанс',
  'Neural Beats AI': 'Нейронные ритмы ИИ',
  'AI Picks for You': 'ИИ-подборки для вас',
  'Neural Mix': 'Нейро-микс',
  'Library Stats': 'Статистика библиотеки',
  'Music': 'Музыка',
  'Movies': 'Фильмы',
  'Photos': 'Фотографии',
  'Podcasts': 'Подкасты',
  'tracks': 'треков',
  'titles': 'фильмов',
  'items': 'файлов',
  'series': 'серий',
  'Playback Queue': 'Очередь воспроизведения',

  // Security
  'Threat Detection': 'Обнаружение угроз',
  'Perimeter Control': 'Контроль периметра',
  'Camera Management': 'Управление камерами',
  'Front Door': 'Главный вход',
  'Backyard': 'Задний двор',
  'Garage': 'Гараж',
  'No Active Threats': 'Нет активных угроз',
  'Last perimeter scan completed 5 minutes ago. All systems nominal.': 'Последнее сканирование периметра завершено 5 минут назад. Все системы в норме.',
  'Security Protocols': 'Протоколы безопасности',
  'Firewall': 'Брандмауэр',
  'Intrusion Detection': 'Обнаружение вторжений',
  'Data Encryption': 'Шифрование данных',
  'Biometric Auth': 'Биометрическая аутентификация',
  'Network Traffic': 'Сетевой трафик',
  'Inbound': 'Входящий',
  'Outbound': 'Исходящий',

  // Header/Footer/Sidebar
  'System Stable': 'Система стабильна',
  'Quantum Sync': 'Квантовая синхронизация',
  'Storage: 1.2 TB Free': 'Хранилище: 1.2 ТБ свободно',
  'Cloud Sync: Active': 'Облачная синхронизация: Активна',
  'Mobile Link: Connected': 'Мобильная связь: Подключена',
  'Shutdown': 'Выключение',
  'Initialization in progress...': 'Идет инициализация...',
  'System Module': 'Системный модуль'
};

for (const [eng, rus] of Object.entries(replacements)) {
  // Use global replacement with word boundaries where appropriate, but standard replaceAll is safer for exact strings
  content = content.split(eng).join(rus);
}

fs.writeFileSync('src/App.tsx', content, 'utf8');
console.log('Translation complete.');
